### ISSUE TITLE
Patched `rjb/extension` method `require` doesn't work with absolute paths

### ISSUE THREAD

**Issue by uvlad7** [arton/rjb#101]
In JRuby I can load jars like this
```ruby
require File.join(Dir.home, '.m2', 'repository', 'com', 'squareup', 'okio', 'okio', '1.15.0', 'okio-1.15.0.jar')
require File.join(Dir.home, '.m2', 'repository', 'com', 'squareup', 'okhttp3', 'okhttp', '3.12.12', 'okhttp-3.12.12.jar')
```
but it doesn't work in `rjb` after `require 'rjb/extension'` because of the following check
```ruby
found_path = $LOAD_PATH.reverse.find{|p| File.exist?(File.join(p,path))}
```
so I had to do this
```ruby
$LOAD_PATH << File.join(Dir.home, '.m2', 'repository')
require File.join('com', 'squareup', 'okio', 'okio', '1.15.0', 'okio-1.15.0.jar')
require File.join('com', 'squareup', 'okhttp3', 'okhttp', '3.12.12', 'okhttp-3.12.12.jar')
```
probably this check should be omitted for absolute paths.

Note: c ruby itself requires absolute path just fine
```ruby
require File.join(Dir.home, 'rjb/lib/rjb/extension')
```

I believe it's possible to reuse Ruby's own [logic](https://github.com/ruby/ruby/blob/0107954f257af6fd4cb280aa36b9b320795c0a86/load.c#L1356) used to resolve load path?

Additionally patch `require_relative` would be nice too

**Comment by arton** [comment]
@uvlad7 Thank you for your report.
rjb-1.7.1.gem skips load path test if an absolute path was given.
