### ISSUE TITLE
RJB and Sidekiq

### ISSUE THREAD

**Issue by thiagocifani** [arton/rjb#37]
Hi, 

I am doing some reports with jasper in a rails application through your gem, but when I try to generate this reports with sidekiq I got a segfault error Any idea how I can fix this problem? Without sidekiq it is working fine, but the amount of data is to big to not use a background job. The log follows below:

[1] pry(#<JasperOnRailsPdf::PdfGenerator>)> jasper_compile_mananger = Rjb::import 'net.sf.jasperreports.engine.JasperCompileManager'
(pry):1: [BUG] Segmentation fault at 0x00000200000088
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

**Comment by arton** [comment]
Sorry for late respond.

Can you import other jasper class other than JaspterCompileManager ?

**Comment by thiagocifani** [comment]
No, I dont. Any class using RJB is not being loaded or imported when I try to use with sidekiq. I have created a api to use the rjb as a standalone rails app. It worked for me, but didnt solve this issue.

**Comment by arton** [comment]
I wonder if you could run the standalone app with $debug=true and $verbose=true, and log standard output and show me it.
