### ISSUE TITLE
Failing to load Rjb

### ISSUE THREAD

**Issue by dtrce** [arton/rjb#39]
I'm trying to use jasper reports with rails but it seems to be failing at this line:

  Rjb::load( classpath, ['-Djava.awt.headless=true','-Xms128M', '-Xmx256M'] )

I'm on Mac El Cap running Java 8. Based on your guide, JAVA_HOME should be pointed to the versions in /System/Library/Frameworks/JavaVM.framework/Libraries/ but I do not have Libraries directory.

**Comment by arton** [comment]
Sorry for your nconvenience

You might read bit old document.
Current version of Rjb automatically points correct Java if it runs on OSX. If you could have some interesting, you may find it in rjb.rb calling '/usr/libexec/java_home'.
Therefore, you should let JAVA_HOME empty.

I'll fix the doucment that you read. I wonder if you could point the document.
Thank you for your cooperation.

**Comment by dtrce** [comment]
I still got the same error after unsetting the JAVA_HOME env variable.

**Comment by arton** [comment]
What is showing on your terminal ?
/usr/libexec/java_home
and
ls `/usr/libexec/java_home`

**Comment by dtrce** [comment]
/usr/libexec/java_home -> /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home

ls /usr/libexec/java_home -> /usr/libexec/java_home

**Comment by arton** [comment]
No. you should put backquote before and after /usr/libexec/java_home.

**Comment by dtrce** [comment]
<img width="395" alt="screenshot 2015-11-22 19 40 21" src="https://cloud.githubusercontent.com/assets/838519/11328083/ea146514-9150-11e5-9cf3-c9aeb83041e3.png">

**Comment by arton** [comment]
It seems fine.
So it should the problem of your rails environment setting.

**Comment by dtrce** [comment]
<img width="1299" alt="screenshot 2015-11-22 20 01 11" src="https://cloud.githubusercontent.com/assets/838519/11328209/d4e0df76-9153-11e5-9fde-545164c8cd8b.png">

**Comment by arton** [comment]
Hi
I can read "can not load rubinius/ffi".
Do you really want to use rubinius to run Rails?

**Comment by dtrce** [comment]
Not sure where it's picking up rubinius from. I'm using rbenv

**Comment by arton** [comment]
I think it's better to re-check your environment.
It seems badly conflicting. In such environment, naturally, Rjb can't run as normal.
