### ISSUE TITLE
Unable to install rjb gem in Server

### ISSUE THREAD

**Issue by shiva-prasad-12** [arton/rjb#40]
I am able to install rjb 1.5.4  in my local system 

But when try install in server getting error like below.

> :/srv/new_rank# gem install rjb
Building native extensions.  This could take a while...
ERROR:  Error installing rjb:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/1.8/gems/rjb-1.5.4/ext
/usr/local/bin/ruby -r ./siteconf20160223-18687-6mws9i-0.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/ruby
extconf.rb:39: JAVA_HOME is not directory. (RuntimeError)

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/1.8/gems/rjb-1.5.4 for inspection.
Results logged to /usr/local/lib/ruby/gems/1.8/extensions/x86_64-linux/1.8-static/rjb-1.5.4/gem_make.out

Please Help me out with this issue to fix

Thank You

**Comment by arton** [comment]
Hi
I wonder if you could attach /usr/local/lib/ruby/gems/1.8/extensions/x86_64-linux/1.8-static/rjb-1.5.4/gem_make.out.

Regards

**Comment by shiva-prasad-12** [comment]
Hi

I had set JAVA_HOME in /etc/environment  as `export` `JAVA_HOME=/usr/lib/jvm/java_version;` and i have changed to ``JAVA_HOME=/usr/lib/jvm/java_version`. Now its working fine.

You can close the ticket now .

 Thank You

**Comment by arton** [comment]
Hi shiva,
I'm glad to hear the good news.

Cheers.
