### ISSUE TITLE
Merge READMEs.

### ISSUE THREAD

**Issue by arbox** [arton/rjb#42]
Hey @arton 

would it be a good idea to merge both README files since GitHub does not work well with the current situation?
I can do that if it's fine with you.

Thanks for RJB :)

**Comment by arton** [comment]
Hi arbox

I'm not certain what README you mean. The sjis and txt ? or http://www.artonx.org/collabo/backyard/?RubyJavaBridge  (I don't forget to move it into github repositry.
By the way, you are very welcome to send me pull requests.

Best regards

**Comment by arbox** [comment]
I meant both japanese and english versions of the README file, because GitHub won't display both. I can compile one documentation file from all three resources.
