### ISSUE TITLE
Line endings in the project

### ISSUE THREAD

**Issue by arbox** [arton/rjb#50]
Hi @arton ,
the repository has now an inconsistent state concerning line endings. It would be better to convert all the files to one type (e.g. Unix-like) and to set `.gitattributes` to automatically convert line endings at every checkout to provide every developer with an appropriate working environment.

If it's OK with you I'll prepare a pull request.

P.S. It will help with the executable bit issue as well.

**Comment by arton** [comment]
Hi arbox
Good point! 
Because I tested, fixed and pushed from my Linux, Mac, Windows boxes by cases. However, I don't well know the use of git configuration such as .gitattributes that you kindly pointed.
I wonder if you could set it into the repositry!
Thank you!
