### ISSUE TITLE
Rjb Segmentation fault at 0x00000000000000

### ISSUE THREAD

**Issue by chinshr** [arton/rjb#54]
When I run celluloid and Rjb (in [shoryuken](https://github.com/phstc/shoryuken)), I get this [segmentation fault](https://gist.github.com/chinshr/d57e53a8028bc7560cf6d19b73d45ec6), when executing this [line](https://github.com/chinshr/diarize-ruby/blob/master/lib/diarize/audio.rb#L37). It works fine when I run form console.

```ruby
  parameter = Rjb::import('fr.lium.spkDiarization.parameter.Parameter').new
```

Note: Problem could be related to [this](https://github.com/arton/rjb/issues/32) and [this](https://github.com/arton/rjb/issues/24) and [stackoverflow question](http://stackoverflow.com/questions/26650068/how-to-use-ruby-java-bridge-with-threads-sidekiq). Works fine on MacOS X.

Configuration:

Ubuntu 14.04
ruby-2.2.3 (installed through rvm)
Java version "1.8.0_111" ([Java Oracle 8 on Ubuntu 14.04](http://askubuntu.com/questions/464755/how-to-install-openjdk-8-on-14-04-lts))
JAVA_HOME=`/usr/lib/jvm/java-8-oracle/`
Rjb 1.5.5

**Comment by arton** [comment]
As you already knew, forking process with loaded JVM in ruby is not stable on some environment. I suppose that because of JVM usage of signals.
IMHO you should spawn celloloid and Rjb scirpt from original shoryuken process. If it needed output of the spawned process, you may pipe between original process and the spawned process with IO.popen or IO.popen2 or 3.
Because of JVM was loaded in the separate process, it should work fine as it run from console.

**Comment by chinshr** [comment]
Got it, I will have to use a pipe between two processes. Thanks for your answer.

**Comment by chinshr** [comment]
@arton Sorry, one more thing, do you think [ruby-drb](http://ruby-doc.org/stdlib-1.9.3/libdoc/drb/rdoc/DRb.html) would work to make a RPC call to a process. It seems the server also uses threads, so I am wondering if I would run into the same issue?

**Comment by arton** [comment]
It's no problem because dRuby is pure ruby solution. No outer dependency is used like Rjb.
The server side of dRuby listens TCP connection in the ruby thread. Once it accepted a client request, it created service thread using ruby's Thread method (means in Ruby context).

**Comment by chinshr** [comment]
Thanks @arton, that's awesome to know! Btw, have updated [diarize-ruby](https://github.com/chinshr/diarize-ruby) to support this using [DRb](http://ruby-doc.org/stdlib-2.0.0/libdoc/drb/rdoc/DRb.html).
