### ISSUE TITLE
RJB and Puma

### ISSUE THREAD

**Issue by ubermanl** [arton/rjb#55]
I'm currently integrating JasperReports to my solution and i kept receiving java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/db_test whenever i wanted to fill my report with data. And even when loading with the right classpath i kept throwing it.
Then (after almost two days of tests) i just figured i switched a few days ago to Puma dev server to do some SSE tests and forgot to get back to thin. So i changed my Gemfile and voila! it just started to work as it should.
Btw im using RoR 4.2 and Puma 3.6.0 with the latest rjb.
Great gem btw!

**Comment by arton** [comment]
Thank you!
