### ISSUE TITLE
No Java runtime present, requesting install.

### ISSUE THREAD

**Issue by maxime-carbonneau** [arton/rjb#56]
On MacOS X Sierra, with jdk1.8.0_121 install, Rjb::import('anything') will halt the process with the message :
No Java runtime present, requesting install.
I had to install Java6 from Apple (https://support.apple.com/kb/DL1572) to fix the issue. Why?

**Comment by arton** [comment]
Short answer => you didn't install Java with OSX standard.
If Java was installed correct way, 
/usr/libexec/java_home
shows right path to Java. Of course Rjb obeys Apple standard.

**Comment by arton** [comment]
What files in the directory? Are there valid Java system?
Or you may set JAVA_HOME environmental variable. Rjb checks the variable prior reading /usr/libexec/java_home for overriding testing Java environment.

**Comment by maxime-carbonneau** [comment]
I try with and without JAVA_HOME. JAVA_HOME was set in my .bash_profile like this :
export JAVA_HOME=$(/usr/libexec/java_home)
jdk1.8.0_121 was installed with the installer downloaded from Oracle (http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
I pretty sure I did it the "correct" way

**Comment by arton** [comment]
Why do you think it as correct way of Apple?
I think it's correct way of Oracle.

**Comment by arton** [comment]
Umm, I also use Orcale Java.

irb(main):001:0> require 'rjb'
=> true
irb(main):002:0> sys = Rjb::import('java.lang.System')
=> #<Rjb::Java_lang_System:0x007ffae88af3c8 @user_initialize=nil>
irb(main):003:0> sys.property('java.version').to_s
=> "1.8.0_20"
irb(main):004:0> sys.property('java.vendor').to_s
=> "Oracle Corporation"

They changed their way between 1.8.0.20 and 1.3.0.121

**Comment by maxime-carbonneau** [comment]
I use the word "correct" because you wrote
> If Java was installed by the correct way

**Comment by maxime-carbonneau** [comment]
I just don't understand why do I need to install Java6 to use your gem.
With Java6 (from Apple) and Java8 (from Oracle) on my system, I get the following output

2.3.1 :001 > require 'rjb'
 => true 
2.3.1 :002 > sys = Rjb::import('java.lang.System')
 => #<Rjb::Java_lang_System:0x007fc06b9f28a0 @user_initialize=nil> 
2.3.1 :003 > sys.property('java.version').to_s
 => "1.8.0_121" 
2.3.1 :004 > sys.property('java.vendor').to_s
 => "Oracle Corporation"

**Comment by arton** [comment]
I remembered the case likes yours.

https://bugs.openjdk.java.net/browse/JDK-7131356

Installing JDK6 is correct workaround I think.

**Comment by twelve17** [comment]
I ran into this problem too, and this fixed it for me:  https://github.com/arton/rjb/issues/30#issuecomment-66909871

My version info:
```
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
```

**Comment by aroop** [comment]
I had the same issue with macOs Catalina. I fixed this issue by adding the following entires to `/Library/Java/JavaVirtualMachines/jdk<???>/Contents/ info.plist` file
- JNI
- BundledApp
- WebStart
- Applets
- CommandLine
