### ISSUE TITLE
Segfault on Ubuntu 16.04 with latest glibc 2.23-0ubuntu9

### ISSUE THREAD

**Issue by AlexKovynev** [arton/rjb#57]
I tried all finded versions of JDK, results the same.
Rjb::load( '.', ['-Djava.awt.headless=true','-Xms128M', '-Xmx512M', '-Dfile.encoding=UTF-8'] )

**Comment by AlexKovynev** [comment]
The same with debian 8.8 mint edition with all updates but older glibc. Look like some security update destroy my vacation:(

**Comment by AlexKovynev** [comment]
Something strange, all fine with fresh firmware and kernel 4.8.0-53, only. Maybe firmware broken.

**Comment by davidkiser** [comment]
FYI,  this was most likely your issue

https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1699772

These hit me too,  I was able to get around it temporarily until  they fix the kernel issue by setting JAVA_TOOL_OPTIONS=-Xss1280k
