### ISSUE TITLE
Rjb::throw() does nothing

### ISSUE THREAD

**Issue by anonym** [arton/rjb#59]
Test case:
```
require 'rjb'
Rjb::load
begin
  Rjb::throw('java.lang.NumberFormatException', 'test')
  Rjb::throw(Rjb::import('java.lang.NumberFormatException').new('test'))
rescue NumberFormatException => e
  puts "I expect a NumberFormatException to be thrown"
rescue Exception => e
  puts "I at least expect *some* excetpion to be thrown"
else
  puts "Unexpectedly no exception is thrown"
end
```
I get:
```
Unexpectedly no exception is thrown
```

Platform: Debian Sid (Linux) on x86_64
rjb: 1.5.5
Ruby: 2.3.5
OpenJDK JRE: 8u151

**Comment by arton** [comment]
Thank you for your report.
I'll investigate it.

**Comment by arton** [comment]
Hi anonym,
Rjb::throw throws the specified exception in Java world. It does not raise an exception in Ruby world.
Therefore, rescue does not have any effects in ruby script for Rjb::throw. It should catch in Java program.
