### ISSUE TITLE
Outdated release notes

### ISSUE THREAD

**Issue by mensfeld** [arton/rjb#79]
Hey, I noticed that the homepage points out to this page for release notes: https://www.artonx.org/collabo/backyard/?RjbReleaseNotes but it seems heavily outdated 1.0.1 while the gem is in 1.6.4. Thanks!

**Comment by arton** [comment]
Hi mensfeld,
Thank you for your notice about my ruined page.
Now I linked to ChangeLog.

**Comment by mensfeld** [comment]
@arton thank you <3
