### ISSUE TITLE
Java throws an exception at RJB loading time

### ISSUE THREAD

**Issue by bmulholland** [arton/rjb#85]
We use rjb in our Rails app. On Friday, this began segfaulting when we use it. [Segfault trace is here](https://gist.github.com/bmulholland/c542f5c4c00728f602be9cb8edfdd819) (it's too long for posting in the issue) -- I simply fired up a rails console on prod and ran what you see.

On further investigation, this happens only one some deploys of our code -- even if the deployed code is identical. Once deployed to Heroku, the releases are consistent: when we roll back to them, the ones that can load the library via rjb without issue always do so. And the ones that segfault also always segfault, even when we roll back to them. Again, even with identical commits in those releases. We have not changed anything related to this area for at least week, and due to the inconsistent nature of the segfault, we have no idea what might have triggered this.

One (perhaps) clue is that Heroku also had some issues with bundler on Friday, and we've had to purge the Heroku cache to make deploys work. Still, that seems quite unrelated to rjb.

We're completely out of ideas here. Any pointers?

**Comment by bmulholland** [comment]
More findings: this is independent of rails. If I fire up a bare `irb` on one of the non-working deployments, require rjb, and do the Rjb.load, it still segfaults. That backtrace is simpler, of course. [Here it is.](https://gist.github.com/bmulholland/e3139509051bea81f7ebc22dbff3123d)

**Comment by bmulholland** [comment]
Update: I found an error! But I had to turn on ruby verbose mode to get it. Shouldn't errors like this be handled in some way rather than segfaulting? It would have been nice to have seen this in any output much sooner...

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: jp/co/infoseek/hp/arton/rjb/RBridge has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by bmulholland** [comment]
That gave me enough of a lead to try an experiment, where I confirmed that manually setting a version on Heroku would fix the problem. It seems that some releases were getting assigned a version of Java that rjb wasn't supported. I don't understand what part that could have been, considering the OpenJDK version output on the machine was always the same, but I haven't seen any errors since then.

That means that, for rjb, the fix I'm requesting here is to please display these errors properly, and to not segfault when they happen.

**Comment by bmulholland** [comment]
No apologies necessary :). I'm glad I figured out in the end.

Would you prefer that I create a fresh issue specifically for raising a proper exception (and not segfaulting) in this case?

**Comment by arton** [comment]
Thank you for your proposal, however it's clear to the reason of (not yet here) the patch.
I wonder if you could change the titile of this issue for example 'Java throws an exception at RJB loading time'.
Your investion is really helpful, thanks again.
