### ISSUE TITLE
Too many warning 'undefining the allocator of T_DATA class'

### ISSUE THREAD

**Issue by arton** [arton/rjb#93]

**Comment by chaadow** [comment]
Hi @arton Unfortunately i'm not an expert. However I believe this PR can help you fix this issue https://github.com/libgit2/rugged/pull/935

I have many warnings as well.

**Comment by chaadow** [comment]
`/app/vendor/bundle/ruby/3.2.0/gems/rjb-1.6.6/lib/rjb/extension.rb:91: warning: undefining the allocator of T_DATA class Rjb::Java_util_Date`

**Comment by arton** [comment]
Thanks chaadow, I created 52de28d.
After checking with ruby2.x, I'll merge it.
